Name:           perl-Geo-IP
Version:        1.38
Release:        1%{?dist}
Summary:        Look up location and network information by IP Address
License:        CHECK(Distributable)
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Geo-IP/
Source0:        http://www.cpan.org/authors/id/B/BO/BORISZ/Geo-IP-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module uses a file based database. This database simply contains IP
blocks as keys, and countries as values. This database should be more
complete and accurate than reverse DNS lookups.

%prep
%setup -q -n Geo-IP-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Geo*
%{_mandir}/man3/*

%changelog
* Tue Feb 02 2010 David Hrbáč <david@hrbac.cz> 1.38-1
- Specfile autogenerated by cpanspec 1.78.
